### ISSUE TITLE
[TRACKER] New nodes in the works

### ISSUE THREAD

**Issue by paddy-exe** [paddy-exe/GodotVisualShader-Extras#5]
## General / Usability
- [ ] Sphere Mask (masks the output of another node in a sphere shape (with smooth falloff))
- [ ] Dither Node [(see here)](https://mtldoc.com/metal/2022/11/20/shaders-explained-dithering)

## Sky Shader
- [ ] Mie Scattering [(Wikipedia article)](https://en.wikipedia.org/wiki/Mie_scattering)
- [ ] Rayleigh Scattering [(Wikipedia article)](https://de.wikipedia.org/wiki/Rayleigh-Streuung)
    - Phase function (Henyey-Greenstein) [(Scientific paper)](https://www.astro.umd.edu/~jph/HG_note.pdf)
- [ ] Raymarching function (to give a volumetric effect to clouds) [(see here)](https://youtu.be/Qj_tK_mdRcA)

## Water Shader
- [ ] Beer's Law [(Wikipedia article)](https://en.wikipedia.org/wiki/Beer–Lambert_law)
- [ ] Phase function (Henyey-Greenstein) [(Scientific paper)](https://www.astro.umd.edu/~jph/HG_note.pdf)
